export const START_FETCHING_OUR_TEAM_CONTENT = 'START_FETCHING_OUR_TEAM_CONTENT';
export const FETCHING_OUR_TEAM_CONTENT_SUCCESS = 'FETCHING_OUR_TEAM_CONTENT_SUCCESS';
export const FETCHING_OUR_TEAM_CONTENT_FAILURE = 'FETCHING_OUR_TEAM_CONTENT_FAILURE';

export const OUR_TEAM_SPINNER_STARTS = 'OUR_TEAM_SPINNER_STARTS'
export const OUR_TEAM_SPINNER_STOPS = 'OUR_TEAM_SPINNER_STOPS'
export const START_FETCHING_OUR_TEAM_CONTENT_WITH_SPINNER = 'START_FETCHING_OUR_TEAM_CONTENT_WITH_SPINNER'

// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
